per_device_train_batch_size: 8
per_device_eval_batch_size: 8
per_device_test_batch_size: 8
gradient_accumulation_steps: 9
eval_steps: 150
save_steps: 150
# per_device_train_batch_size * gradient_accumulation_steps = 72
# eval_steps / gradient_accumulation_steps = 8.33