model_id: "Unbabel/TowerInstruct-7B-v0.2" # "Unbabel/TowerInstruct-7B-v0.2" "meta-llama/Llama-3.2-1B-Instruct"
comet_qe_baseline: "wmt22-cometkiwi-da"
comet_ref_based: "XCOMET-XL"
force_decoding: False
