model_id: "Unbabel/TowerInstruct-7B-v0.2" # "Unbabel/TowerInstruct-7B-v0.2" "meta-llama/Llama-3.2-1B-Instruct"
train_src_path: "fairseq/examples/confidence_aware_ssl/data/ParaCrawl/train.5M.dedup.en"
train_tgt_path: "fairseq/examples/confidence_aware_ssl/data/ParaCrawl/train.5M.dedup.de"
dev_src_path: "fairseq/examples/confidence_aware_ssl/data/ParaCrawl/dev.en"
dev_tgt_path: "fairseq/examples/confidence_aware_ssl/data/ParaCrawl/dev.de"
test_src_path: "fairseq/examples/confidence_aware_ssl/data/ParaCrawl/test.en"
test_tgt_path: "fairseq/examples/confidence_aware_ssl/data/ParaCrawl/test.de"
src_lang: "English"
tgt_lang: "German"
dataname: "ParaCrawl"
max_length: 896

freeze_base_model: True
init_sigmoid_head_from_softmax_head: True
negative_sampling: True
negative_sampling_ratio: 10
negative_sampling_method: "token_freq,softmax_probs"
negative_sampling_avoid_dominant: True
weight_positive: "balance"